spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: 123456
          type: com.alibaba.druid.pool.DruidDataSource
        slave:
          url: jdbc:oracle:thin:@localhost:1521:orcl
          driver-class-name: oracle.jdbc.driver.OracleDriver
          username: test
          password: test
          type: com.alibaba.druid.pool.DruidDataSource
logging:
  level:
    com.baomidou: debug
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml